const IS_LOGGED_UPDATED = 'IS_LOGGED/UPDATED';
const TOKEN_UPDATED = 'TOKEN/UPDATED';
const SHOW_LOGIN_CARD_UPDATED = 'SHOW_LOGIN_CARD/UPDATED';
const SHOW_SIGNUP_CARD_UPDATED = 'SHOW_SIGNUP_CARD/UPDATED';
const IS_DESKTOP_UPDATED = 'IS_DESKTOP/UPDATED';
const USER_INFO_UPDATED = 'USER_INFO/UPDATED';

/** Http codes */
const AUTHORIZED = 200;
const SUCCESS = 200;
const CREATED = 201;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;

const LOGGED_USER = 'loggedUser';
const USER_TOKEN = 'userToken';

const SESSION = 'session';

const PASS_REGEX = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])[0-9a-zA-Z]{6,}$/;
const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export {
  IS_LOGGED_UPDATED,
  TOKEN_UPDATED,
  SHOW_LOGIN_CARD_UPDATED,
  IS_DESKTOP_UPDATED,
  SHOW_SIGNUP_CARD_UPDATED,
  UNAUTHORIZED,
  SUCCESS,
  AUTHORIZED,
  CREATED,
  BAD_REQUEST,
  LOGGED_USER,
  USER_TOKEN,
  PASS_REGEX,
  EMAIL_REGEX,
  USER_INFO_UPDATED,
  SESSION,
};
