version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./api/data:/var/lib/postgresql/data
      # - ./api/db:/docker-entrypoint-initdb.d/
      # copy the sql script to create tables
      - ./api/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    ports:
      - '5432:5432'
    networks:
      - matcha-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: matcha
  
  adminer:
    container_name: adminer
    depends_on:
      - postgres
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - matcha-network

  api:
    container_name: api
    depends_on:
      - postgres
    restart: unless-stopped
    env_file: ./api/.env
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - matcha-network
    volumes:
      - .:/api
      - /api/node_modules

  # front:
  #   container_name: front
  #   build:
  #     context: ./front/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  


networks:
  matcha-network:
    driver: bridge